Add fpslogger
servacc/CVSLogger pull request #1
Opened 2021-02-15 13:35 UTC by ssysoenko

Use SPDLOG_FMT_EXTERNAL by default
Move DefaultLoggerFactory to src
Inherit ILogger from enable_shared_from_this
Add ILogger to processArg params
Update spdlog to 1.8.2

2021-02-15 15:27 UTC, roman-orekhov commented on CMakeLists.txt
> +find_package(fmt REQUIRED)
won't work if fmt is added to project via add_subdirectory previously

2021-02-15 15:28 UTC, roman-orekhov commented on CMakeLists.txt
> +        src/default/defaultfactory.hpp
why mix *.h and *.hpp when both are C++?

2021-02-15 15:43 UTC, roman-orekhov commented on include/cvs/logger/ilogger.h
> +  typename Strategy<T>::Type processArg(const std::shared_ptr<ILogger>&, Level, const T& arg) {
I don't see a use case for this, not in this commit for sure. Don't think it's a necessary change for this commit -- better to include it with the change where it's needed or in a separate commit right before such change

2021-02-15 15:47 UTC, roman-orekhov requested changes
Generally I'd prefer splitting commits into parts dealing with particular additions: some build-only fixes, some about feature1, some about feature2, etc

2021-02-16 08:53 UTC, ssysoenko commented on include/cvs/logger/ilogger.h
> +  typename Strategy<T>::Type processArg(const std::shared_ptr<ILogger>&, Level, const T& arg) {
Difference? In the release, messages will still get mixed up.

2021-02-16 10:49 UTC, roman-orekhov commented on include/cvs/logger/ilogger.h
> +  typename Strategy<T>::Type processArg(const std::shared_ptr<ILogger>&, Level, const T& arg) {
> 
> 
> Difference? In the release, messages will still get mixed up.

I don't get the answer. What can be different if the parameter isn't used anywhere? Is it just to keep shared_ptr alive at certain use case? Can you describe the use case?

2021-02-16 16:08 UTC, roman-orekhov approved these changes

2021-02-16 20:42 UTC, Aldrog approved these changes

2021-02-17 11:21 UTC, merged