Commonlib
servacc/CVSLogger pull request #4
Opened 2021-03-25 12:11 UTC by ssysoenko

2021-03-30 23:27 UTC, efimov-evgeniy requested changes

2021-03-30 23:27 UTC, efimov-evgeniy commented on include/cvs/logger/loggable.hpp
> +  Loggable(std::string                        name = boost::core::demangle(typeid(T).name()),
Почему не константная ссылка?
Конструктор лучше пометить как explicit

2021-03-30 23:27 UTC, efimov-evgeniy commented on src/logging.cpp
> +static Sinks default_sinks =
Зачем static?

2021-03-30 23:27 UTC, efimov-evgeniy commented on src/logging.cpp
> +  NOSINK  = 0,
Если я правильно понял смысл (и это не пародия на русский акцент =) ), то, может, лучше NO_SINK?

2021-03-30 23:27 UTC, efimov-evgeniy commented on src/logging.cpp
> +auto createSink(bool enable) {
Не совсем понятно что значит "enable"

2021-03-30 23:27 UTC, efimov-evgeniy commented on src/logging.cpp
> +  return std::make_shared<spdlog::logger>(name, std::begin(sinks), std::end(sinks));
Я думаю, что тут можно заменить на вызов конструктора с initializer_list

2021-03-30 23:27 UTC, efimov-evgeniy commented on include/cvs/logger/logging.hpp
> +#define LOG_TRACE(CH, ...)                        \
А всё это счастье нельзя в функцию вынести?

2021-03-30 23:27 UTC, efimov-evgeniy commented on include/cvs/logger/logging.hpp
> +               Args&&... args) {
Три аргумента выровнял, а чётвёртый не стал.

2021-03-30 23:27 UTC, efimov-evgeniy commented on include/cvs/logger/loggable.hpp
> +  LoggerPtr&       logger() { return log; }
[[nodiscard]]

2021-03-30 23:27 UTC, efimov-evgeniy commented on src/logging.cpp
> +constexpr bool  operator&(Sinks s0, Sinks s1) { return (int(s0) & int(s1)) != 0; }
Как-то вообще не очевидно что делает этот оператор

2021-03-30 23:27 UTC, efimov-evgeniy commented on src/logging.cpp
> +enum class Sinks : int {
Почему int?

2021-03-30 23:27 UTC, efimov-evgeniy commented on src/logging.cpp
> +                      CVSCFG_VALUE_OPTIONAL(sink, int))
Если определить оператор >> для istream и Sinks, то можно пихать прямо нужный тип

2021-03-30 23:27 UTC, efimov-evgeniy commented on src/logging.cpp
> +enum class Sinks : int {
Перечисления обычно именуются в единственном числе

2021-03-30 23:27 UTC, efimov-evgeniy commented on src/logging.cpp
> +void configureLogger(LoggerPtr logger, cvs::common::Config& cfg) {
Разве функция не подразумевает возможность неудачи?

2021-03-30 23:27 UTC, efimov-evgeniy commented on src/logging.cpp
> +      "cvslogger"s, [](cvs::common::Config cfg) -> LoggerPtr {
Здесь можно лямбду выровнять по первому аргументу функции registrate

2021-03-30 23:27 UTC, efimov-evgeniy commented on src/logging.cpp
> +        if (cfg_struct_opt) {
Можно инвертировать условие

2021-03-30 23:27 UTC, efimov-evgeniy commented on src/opencvhelper.cpp
> +    std::filesystem::temp_directory_path() / "cvslogger";
Может выбросить исключение, что не очень хорошо

2021-03-30 23:27 UTC, efimov-evgeniy commented on include/cvs/logger/argumentpreprocessor.hpp
> +struct ArgumentPreprocessor {
Может, лучше через наследование? Или, по крайней мере, запретить инстанциацию вне специализации.

2021-03-30 23:27 UTC, efimov-evgeniy commented on src/opencvhelper.cpp
> +void confugureLoggerAndOpenCVHelper(std::shared_ptr<spdlog::logger>& logger,
Очепятка в "configure"

2021-03-31 05:59 UTC, ssysoenko commented on include/cvs/logger/logging.hpp
> +               Args&&... args) {
Это у clang-format, видимо, с "..." башню рвет. Тут надо форматирование отключать, что такое себе.

2021-03-31 07:11 UTC, ssysoenko commented on src/logging.cpp
> +                      CVSCFG_VALUE_OPTIONAL(sink, int))
Было бы круто указывать в массиве текстовыми названиями. Но, насколько я понял, конфиг так не умеет.

2021-03-31 07:14 UTC, ssysoenko commented on src/logging.cpp
> +      "cvslogger"s, [](cvs::common::Config cfg) -> LoggerPtr {
так clang-format решил

2021-03-31 18:10 UTC, ssysoenko commented on include/cvs/logger/argumentpreprocessor.hpp
> +struct ArgumentPreprocessor {
Не понял что имеется ввиду и зачем.

2021-03-31 19:10 UTC, efimov-evgeniy commented on include/cvs/logger/argumentpreprocessor.hpp
> +struct ArgumentPreprocessor {
Ну у тебя, как я понял, подразумевается, что пользователь должен реализовать специализацию ArgumentPreprocessor для своего типа. Почему это не сделать наследованием?
И если у тебя не подразумевается использование ArgumentPreprocessor для произвольного аргумента шаблона, то может лучше запретить это явно?

2021-03-31 19:11 UTC, efimov-evgeniy commented on src/logging.cpp
> +      "cvslogger"s, [](cvs::common::Config cfg) -> LoggerPtr {
Ave clang-format!

2021-03-31 19:11 UTC, efimov-evgeniy commented on src/logging.cpp
> +                      CVSCFG_VALUE_OPTIONAL(sink, int))
Не понял что конкретно имеется в виду. Пример можно?

2021-04-08 14:54 UTC, roman-orekhov commented on include/cvs/logger/loggable.hpp
> +                    std::optional<cvs::common::Config> cfg = std::nullopt) {
Это даёт имя типа вместе с неймспейсами и параметрами шаблона? Если да, то по дефолту будут длинные (и потому медленные) имена логгеров.

2021-04-08 14:58 UTC, roman-orekhov commented on include/cvs/logger/logging.hpp
> +
Это совершенно не равноценно тому, что было. Раньше аргументы логирования не вычислялись, если уровень был не достаточный. Теперь вычисляются всегда. Соответственно больше лишней работы при отключённом уровне логирования.

2021-04-08 15:01 UTC, roman-orekhov commented on src/opencvhelper.cpp
> +
Хех, вот лишь бы не использовать fmtlib :) которая ведь и так тянется везде, где есть логгер.

2021-04-09 09:09 UTC, ssysoenko commented on include/cvs/logger/loggable.hpp
> +                    std::optional<cvs::common::Config> cfg = std::nullopt) {
Логгер вообще штука не самая быстрая. И приходится сравнивать информативность со скоростью. Вообще штуки не сравнимые.

2021-04-09 09:10 UTC, ssysoenko commented on include/cvs/logger/logging.hpp
> +
Блин. А я вспоминал зачем у меня борода из if-ов была написана так и не вспомнил. Буду возвращать!

2021-04-09 09:11 UTC, ssysoenko commented on src/opencvhelper.cpp
> +
Точно! Их же есть тут в любом случае. :)

2021-04-09 10:34 UTC, roman-orekhov commented on include/cvs/logger/loggable.hpp
> +                    std::optional<cvs::common::Config> cfg = std::nullopt) {
Напомню, что spdlog ты выбрал как бэкенд среди прочего за то, что он самый быстрый логгер был согласно какой-то статье на хабре. Ну и судя по некоторым постам на его гитхабе, он для встроенных систем применяется, так что он изначально быстрый

2021-04-09 10:34 UTC, roman-orekhov commented on src/opencvhelper.cpp
> +
В ней есть и для time форматирование ЕМНИП

2021-04-09 11:32 UTC, ssysoenko commented on include/cvs/logger/loggable.hpp
> +                    std::optional<cvs::common::Config> cfg = std::nullopt) {
На скорость логеров я вообще не смотрел. Статья на хабре с обзором была, и, вроде, там сравнивали и производительность. А spdlog был выбран в совокупности за то, что уже с ним работал и нареканий к нему у меня особых не было, не было нареканий у знакомых его использовавших и вполне себе наплохо о нем было написано на хабре.
Кстати, а какое будет замедление при конкатенации строк различной длинны?

2021-04-09 11:41 UTC, roman-orekhov commented on include/cvs/logger/loggable.hpp
> +                    std::optional<cvs::common::Config> cfg = std::nullopt) {
Замедление от копирования этих строк идёт. Строка названия логгера копируется в буфер (в котором уже лежит форматированное время) всякий раз при логировании. Чем меньше длина строки, тем, очевидно, меньше инструкций на копирование.

2021-04-09 14:26 UTC, ssysoenko commented on include/cvs/logger/loggable.hpp
> +                    std::optional<cvs::common::Config> cfg = std::nullopt) {
Т.е. ты предполагаешь, что там копирование идет поэлементно, а не блоком? Потому как поэлементно разница есть, а вот блоком - вряли.

2021-04-10 13:22 UTC, roman-orekhov commented on include/cvs/logger/loggable.hpp
> +                    std::optional<cvs::common::Config> cfg = std::nullopt) {
Наверно ты не понял, про что я спрашивал... boost::core::demangle(typeid(T).name()) для FpsLogger выдаёт какую строку? "FpsLogger" или, например, "common::logging::FpsLogger"? В результате в логе быдет одна из этих строк размножена. Ну и чем строка длиннее, тем дольше будет её выводить в любой из синков. Вывод в синк сам по себе подразумевает копирование. А по архитектуре spdlog, ЕМНИП, идёт форматирование один раз (и в этот момент строка с именем логгера копируется в итоговую, отформатированную, строку, которая пойдёт в синки), и потом форматированная строка копируется в промежуточные буфера, а потом мувится в синки. Если синков несколько и они не синхронные, то там ещё и в промежуточные буферы именно копирование будет, а не move.

2021-04-13 10:29 UTC, ssysoenko commented on include/cvs/logger/argumentpreprocessor.hpp
> +struct ArgumentPreprocessor {
Все еще не понимаю про что ты.
ArgumentPreprocessor обрабатывает любой аргумент (кроме логера и строки формата) внезависимости от типа. Что должно дать наследование? Кто должен создавать экземпляр? Как определять какого именно наследника создавать? Зачем это все надо?

2021-04-13 10:40 UTC, ssysoenko commented on include/cvs/logger/loggable.hpp
> +                    std::optional<cvs::common::Config> cfg = std::nullopt) {
Ну какая-нить буква/цифра - это не информативно. Если настолько критична скорость - можно задать имя в конструкторе. И все же это надуманная проблема имхо.

2021-04-15 10:51 UTC, ssysoenko commented on src/logging.cpp
> +                      CVSCFG_VALUE_OPTIONAL(sink, int))
Если запихать енум то будет цифра. Гораздо понятнее будет если указывать надписью:
`"sink" : "std&systemd"`
или
`"sink" : ["std", "systemd"]`

2021-04-15 14:22 UTC, efimov-evgeniy commented on src/logging.cpp
> +                      CVSCFG_VALUE_OPTIONAL(sink, int))
Не вижу в этом смысла. Если ты определил раньше `enum Sink`, то понятно, что если ты считываешь из конфига, результат будет из этого перечисления. Зачем объявлять тип прямо в конфиге?

2021-05-06 10:01 UTC, efimov-evgeniy approved these changes

2021-05-06 13:15 UTC, Aldrog requested changes

2021-05-06 13:15 UTC, Aldrog commented on src/logging.cpp
> +bool configureLogger(LoggerPtr logger, cvs::common::Config& cfg) {
Здесь можно было бы принимать просто ссылку на `spdlog::logger`

2021-05-06 13:15 UTC, Aldrog commented on src/logging.cpp
> +  auto cfg_struct_opt = cfg.parse<LoggerConfig>();
Кажется, то, что `Config::parse` не объявлен как `const` — это баг в CVSCommon. Было бы неплохо его исправить и принимать `const Config &`

2021-05-06 13:15 UTC, Aldrog commented on src/logging.cpp
> +LoggerPtr createLogger(const std::string& name, std::optional<common::Config> config) {
Здесь и далее config можно сделать константной ссылкой, копировать его совершенно ни к чему.

2021-05-07 09:38 UTC, ssysoenko commented on src/logging.cpp
> +  auto cfg_struct_opt = cfg.parse<LoggerConfig>();
Предлагаю пока не обращать внимание на то что связано с конфигом. Есть идея его упростить значительно.

2021-05-12 14:34 UTC, Aldrog requested changes

2021-05-12 14:34 UTC, Aldrog commented on include/cvs/logger/logging.hpp
> +bool      configureLogger(const LoggerPtr&, cvs::common::Config&);
Почему не `spdlog::logger &`? Функционал смартпойнтера тут не нужен, и сигнатура будет отражать, что состояние логгера меняется.

2021-05-12 14:34 UTC, Aldrog commented on include/cvs/logger/opencvhelper.hpp
> +void configureLoggerAndOpenCVHelper(const std::shared_ptr<spdlog::logger>& logger,
Аналогично.

2021-05-13 11:04 UTC, Aldrog approved these changes

2021-05-13 12:55 UTC, merged